site_name: Portifólio IA

repo_name: portifolio-IA
repo_url: https://github.com/JeffersonSenaa/portifolio-IA

theme: 
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette: 
    - scheme: default
      accent: indigo
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      accent: indigo
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JeffersonSenaa/portifolio-IA
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jefferson-sena/

nav:
  - Home: index.md
  - Portifolio 2: portifolio-2.md
  - Portifolio 3: portifolio-3.md